language: android
env:
  global:
    - SYSTEM_TYPE="CI"  # Environment variable for a performance optimization during compile
  matrix:

    # - ANDROID_TARGET=android-15  ANDROID_ABI=armeabi-v7a ANDROID_ADDON=addon-google_apis-google-15 ANDROID_SYS_IMG=sys-img-armeabi-v7a-android-15
    # - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a ANDROID_ADDON=addon-google_apis-google-19 ANDROID_SYS_IMG=sys-img-armeabi-v7a-android-19
    # - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a ANDROID_ADDON=addon-google_apis-google-21 ANDROID_SYS_IMG=sys-img-armeabi-v7a-android-21
    # - ANDROID_TARGET=android-19  ANDROID_ABI=x86 ANDROID_ADDON=addon-google_apis-google-19 ANDROID_SYS_IMG=sys-img-x86-android-19
    # - ANDROID_TARGET=android-15  ANDROID_ABI=x86

android:
  components:

    # All the build system components should be at the latest version
    - tools
    - platform-tools
    - build-tools-21.1.2
    - android-21

    # The libraries we can't get from Maven Central or similar
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    # - $ANDROID_ADDON

    # Specify all the emulator targets we'll need
    # - $ANDROID_SYS_IMG

script:
  - ./gradlew clean assembleProductionRelease testProductionDebug  # Make sure we can build and run tests

# Emulator Management: Create, Start and Wait
# before_script:

  # Use the matrix values to set up the AVDs
  # - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  # - emulator -avd test -no-skin -no-audio -no-window &
  # - android-wait-for-emulator
  # - adb shell input keyevent 82 &

notifications:
  email: true