language: android
env:
  global:
    - SYSTEM_TYPE="CI"  # Environment variable for a performance optimization during compile
  matrix:

    # Run against v15 & v19 on both ARMv7 and x86 platforms
    # Except travis is still flaky so for now only run against 1 target
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
    # - ANDROID_TARGET=android-15  ANDROID_ABI=armeabi-v7a
    # - ANDROID_TARGET=android-19  ANDROID_ABI=x86
    # - ANDROID_TARGET=android-15  ANDROID_ABI=x86

android:
  components:

    # All the build system components should be at the latest version
    - tools
    - platform-tools
    - build-tools-20.0.0
    - android-20

    # The libraries we can't get from Maven Central or similar
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify all the emulator targets we'll need
    - sys-img-armeabi-v7a-android-19
    # - sys-img-armeabi-v7a-android-15
    # - sys-img-x86-android-19
    # - sys-img-x86-android-15

script:
  - ./gradlew build connectedCheck  # run tests and lint

# Emulator Management: Create, Start and Wait
before_script:

  # Use the matrix values to set up the AVDs
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &