// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/projects/TruckMuncher-Protos/com/truckmuncher/api/auth.proto
package com.truckmuncher.api.auth;

import retrofit.Callback;
import retrofit.RetrofitError;
import retrofit.http.Body;
import retrofit.http.POST;

/**
 * The AuthService is used to sign in and out of TruckMuncher.
 */
public interface AuthService {
  /**
   * Returns the full User model plus a session token.
   */
  @POST("/com.truckmuncher.api.auth.AuthService/getAuth")
  AuthResponse getAuth(@Body AuthRequest request)
      throws RetrofitError;

  /**
   * Returns the full User model plus a session token.
   */
  @POST("/com.truckmuncher.api.auth.AuthService/getAuth")
  void getAuth(@Body AuthRequest request, Callback<AuthResponse> callback);
  /**
   * Deletes an existing session if it exists.
   */
  @POST("/com.truckmuncher.api.auth.AuthService/deleteAuth")
  DeleteAuthResponse deleteAuth(@Body AuthRequest request)
      throws RetrofitError;

  /**
   * Deletes an existing session if it exists.
   */
  @POST("/com.truckmuncher.api.auth.AuthService/deleteAuth")
  void deleteAuth(@Body AuthRequest request, Callback<DeleteAuthResponse> callback);
}
