// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/Dropbox/workspace/TruckMuncher-Protos/com/truckmuncher/api/trucks.proto
package com.truckmuncher.api.trucks;

import com.squareup.wire.Message;

public final class ServingModeResponse extends Message {

  public ServingModeResponse() {
  }

  private ServingModeResponse(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof ServingModeResponse;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<ServingModeResponse> {

    public Builder() {
    }

    public Builder(ServingModeResponse message) {
      super(message);
    }

    @Override
    public ServingModeResponse build() {
      return new ServingModeResponse(this);
    }
  }
}
