// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/Dropbox/workspace/TruckMuncher-Protos/com/truckmuncher/api/trucks.proto
package com.truckmuncher.api.trucks;

import com.squareup.wire.Message;

public final class TruckForVendorRequest extends Message {

    public TruckForVendorRequest() {
    }

    private TruckForVendorRequest(Builder builder) {
        setBuilder(builder);
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof TruckForVendorRequest;
    }

    @Override
    public int hashCode() {
        return 0;
    }

    public static final class Builder extends Message.Builder<TruckForVendorRequest> {

        public Builder() {
        }

        public Builder(TruckForVendorRequest message) {
            super(message);
        }

        @Override
        public TruckForVendorRequest build() {
            return new TruckForVendorRequest(this);
        }
    }
}
