// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/Dropbox/workspace/TruckMuncher-Protos/com/truckmuncher/api/trucks.proto
package com.truckmuncher.api.trucks;

import com.squareup.wire.Message;

public final class TrucksForVendorRequest extends Message {

    public TrucksForVendorRequest() {
    }

    private TrucksForVendorRequest(Builder builder) {
        setBuilder(builder);
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof TrucksForVendorRequest;
    }

    @Override
    public int hashCode() {
        return 0;
    }

    public static final class Builder extends Message.Builder<TrucksForVendorRequest> {

        public Builder() {
        }

        public Builder(TrucksForVendorRequest message) {
            super(message);
        }

        @Override
        public TrucksForVendorRequest build() {
            return new TrucksForVendorRequest(this);
        }
    }
}
