// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/Dropbox/workspace/TruckMuncher-Protos/com/truckmuncher/api/trucks.proto
package com.truckmuncher.api.trucks;

import retrofit.Callback;
import retrofit.RetrofitError;
import retrofit.http.Body;
import retrofit.http.POST;

/**
 * TODO
 */
public interface TruckService {
  /**
   * Get the locations of active food trucks in the Region in which the search is performed.
   */
  @POST("/com.truckmuncher.api.trucks.TruckService/getActiveTrucks")
  ActiveTrucksResponse getActiveTrucks(@Body ActiveTrucksRequest request)
      throws RetrofitError;

  /**
   * Get the locations of active food trucks in the Region in which the search is performed.
   */
  @POST("/com.truckmuncher.api.trucks.TruckService/getActiveTrucks")
  void getActiveTrucks(@Body ActiveTrucksRequest request, Callback<ActiveTrucksResponse> callback);
  /**
   * Get the profiles of all the food trucks in the user's Region.
   */
  @POST("/com.truckmuncher.api.trucks.TruckService/getTruckProfiles")
  TruckProfilesResponse getTruckProfiles(@Body TruckProfilesRequest request)
      throws RetrofitError;

  /**
   * Get the profiles of all the food trucks in the user's Region.
   */
  @POST("/com.truckmuncher.api.trucks.TruckService/getTruckProfiles")
  void getTruckProfiles(@Body TruckProfilesRequest request, Callback<TruckProfilesResponse> callback);
  /**
   * Get the profiles of all the food trucks in the user's region.
   *
   * This call requires Vendor authorization
   */
  @POST("/com.truckmuncher.api.trucks.TruckService/modifyTruckProfile")
  Truck modifyTruckProfile(@Body Truck request)
      throws RetrofitError;

  /**
   * Get the profiles of all the food trucks in the user's region.
   *
   * This call requires Vendor authorization
   */
  @POST("/com.truckmuncher.api.trucks.TruckService/modifyTruckProfile")
  void modifyTruckProfile(@Body Truck request, Callback<Truck> callback);
  /**
   * Get the profiles of all the food trucks in the user's region.
   *
   * This call requires Vendor authorization
   */
  @POST("/com.truckmuncher.api.trucks.TruckService/modifyServingMode")
  ServingModeResponse modifyServingMode(@Body ServingModeRequest request)
      throws RetrofitError;

  /**
   * Get the profiles of all the food trucks in the user's region.
   *
   * This call requires Vendor authorization
   */
  @POST("/com.truckmuncher.api.trucks.TruckService/modifyServingMode")
  void modifyServingMode(@Body ServingModeRequest request, Callback<ServingModeResponse> callback);
}
