// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/Dropbox/workspace/TruckMuncher-Protos/com/truckmuncher/api/healthcheck.proto
package com.truckmuncher.api.healthcheck;

import com.squareup.wire.Message;

public final class HealthRequest extends Message {

    public HealthRequest() {
    }

    private HealthRequest(Builder builder) {
        setBuilder(builder);
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof HealthRequest;
    }

    @Override
    public int hashCode() {
        return 0;
    }

    public static final class Builder extends Message.Builder<HealthRequest> {

        public Builder() {
        }

        public Builder(HealthRequest message) {
            super(message);
        }

        @Override
        public HealthRequest build() {
            return new HealthRequest(this);
        }
    }
}
