// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/projects/TruckMuncher-Protos/com/truckmuncher/api/user.proto
package com.truckmuncher.api.user;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class FavoriteRequest extends Message {

  public static final String DEFAULT_TRUCKID = "";

  /**
   * The unique ID of the favorite truck.
   */
  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public final String truckId;

  public FavoriteRequest(String truckId) {
    this.truckId = truckId;
  }

  private FavoriteRequest(Builder builder) {
    this(builder.truckId);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof FavoriteRequest)) return false;
    return equals(truckId, ((FavoriteRequest) other).truckId);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = truckId != null ? truckId.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<FavoriteRequest> {

    public String truckId;

    public Builder() {
    }

    public Builder(FavoriteRequest message) {
      super(message);
      if (message == null) return;
      this.truckId = message.truckId;
    }

    /**
     * The unique ID of the favorite truck.
     */
    public Builder truckId(String truckId) {
      this.truckId = truckId;
      return this;
    }

    @Override
    public FavoriteRequest build() {
      checkRequiredFields();
      return new FavoriteRequest(this);
    }
  }
}
