// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/projects/TruckMuncher-Protos/com/truckmuncher/api/user.proto
package com.truckmuncher.api.user;

import com.squareup.wire.Message;

public final class GetAccountRequest extends Message {

  public GetAccountRequest() {
  }

  private GetAccountRequest(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof GetAccountRequest;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<GetAccountRequest> {

    public Builder() {
    }

    public Builder(GetAccountRequest message) {
      super(message);
    }

    @Override
    public GetAccountRequest build() {
      return new GetAccountRequest(this);
    }
  }
}
