// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/projects/TruckMuncher-Protos/com/truckmuncher/api/user.proto
package com.truckmuncher.api.user;

import com.squareup.wire.Message;

public final class GetFavoritesRequest extends Message {

  public GetFavoritesRequest() {
  }

  private GetFavoritesRequest(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof GetFavoritesRequest;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<GetFavoritesRequest> {

    public Builder() {
    }

    public Builder(GetFavoritesRequest message) {
      super(message);
    }

    @Override
    public GetFavoritesRequest build() {
      return new GetFavoritesRequest(this);
    }
  }
}
