// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/projects/TruckMuncher-Protos/com/truckmuncher/api/user.proto
package com.truckmuncher.api.user;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;

public final class LinkAccountRequest extends Message {

  public static final Boolean DEFAULT_POSTACTIVITY = false;

  /**
   * If true, a post will be sent to the social media site when a truck goes in to serving mode.
   * This requires the user to be a Vendor, otherwise this field will be ignored.
   */
  @ProtoField(tag = 1, type = BOOL)
  public final Boolean postActivity;

  public LinkAccountRequest(Boolean postActivity) {
    this.postActivity = postActivity;
  }

  private LinkAccountRequest(Builder builder) {
    this(builder.postActivity);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof LinkAccountRequest)) return false;
    return equals(postActivity, ((LinkAccountRequest) other).postActivity);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = postActivity != null ? postActivity.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<LinkAccountRequest> {

    public Boolean postActivity;

    public Builder() {
    }

    public Builder(LinkAccountRequest message) {
      super(message);
      if (message == null) return;
      this.postActivity = message.postActivity;
    }

    /**
     * If true, a post will be sent to the social media site when a truck goes in to serving mode.
     * This requires the user to be a Vendor, otherwise this field will be ignored.
     */
    public Builder postActivity(Boolean postActivity) {
      this.postActivity = postActivity;
      return this;
    }

    @Override
    public LinkAccountRequest build() {
      return new LinkAccountRequest(this);
    }
  }
}
