// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/projects/TruckMuncher-Protos/com/truckmuncher/api/user.proto
package com.truckmuncher.api.user;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;

public final class ModifyAccountRequest extends Message {

  public static final Boolean DEFAULT_POSTTOFB = false;
  public static final Boolean DEFAULT_POSTTOTW = false;

  /**
   * If true, a post will be sent to Facebook when a truck goes in to serving mode.
   * This requires the user to be a Vendor, otherwise this field will be ignored.
   *
   * Will be null if a Facebook account has not been linked.
   */
  @ProtoField(tag = 1, type = BOOL)
  public final Boolean postToFb;

  /**
   * If true, a post will be sent to Twitter when a truck goes in to serving mode.
   * This requires the user to be a Vendor, otherwise this field will be ignored.
   *
   * Will be null if a Twitter account has not been linked.
   */
  @ProtoField(tag = 2, type = BOOL)
  public final Boolean postToTw;

  public ModifyAccountRequest(Boolean postToFb, Boolean postToTw) {
    this.postToFb = postToFb;
    this.postToTw = postToTw;
  }

  private ModifyAccountRequest(Builder builder) {
    this(builder.postToFb, builder.postToTw);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ModifyAccountRequest)) return false;
    ModifyAccountRequest o = (ModifyAccountRequest) other;
    return equals(postToFb, o.postToFb)
        && equals(postToTw, o.postToTw);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = postToFb != null ? postToFb.hashCode() : 0;
      result = result * 37 + (postToTw != null ? postToTw.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ModifyAccountRequest> {

    public Boolean postToFb;
    public Boolean postToTw;

    public Builder() {
    }

    public Builder(ModifyAccountRequest message) {
      super(message);
      if (message == null) return;
      this.postToFb = message.postToFb;
      this.postToTw = message.postToTw;
    }

    /**
     * If true, a post will be sent to Facebook when a truck goes in to serving mode.
     * This requires the user to be a Vendor, otherwise this field will be ignored.
     *
     * Will be null if a Facebook account has not been linked.
     */
    public Builder postToFb(Boolean postToFb) {
      this.postToFb = postToFb;
      return this;
    }

    /**
     * If true, a post will be sent to Twitter when a truck goes in to serving mode.
     * This requires the user to be a Vendor, otherwise this field will be ignored.
     *
     * Will be null if a Twitter account has not been linked.
     */
    public Builder postToTw(Boolean postToTw) {
      this.postToTw = postToTw;
      return this;
    }

    @Override
    public ModifyAccountRequest build() {
      return new ModifyAccountRequest(this);
    }
  }
}
