// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/projects/TruckMuncher-Protos/com/truckmuncher/api/user.proto
package com.truckmuncher.api.user;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;

public final class UnlinkAccountsRequest extends Message {

  public static final Boolean DEFAULT_TWITTER = false;
  public static final Boolean DEFAULT_FACEBOOK = false;

  /**
   * Determines whether or not to unlink your Twitter account.
   */
  @ProtoField(tag = 1, type = BOOL)
  public final Boolean twitter;

  /**
   * Determines whether or not to unlink your Facebook account.
   */
  @ProtoField(tag = 2, type = BOOL)
  public final Boolean facebook;

  public UnlinkAccountsRequest(Boolean twitter, Boolean facebook) {
    this.twitter = twitter;
    this.facebook = facebook;
  }

  private UnlinkAccountsRequest(Builder builder) {
    this(builder.twitter, builder.facebook);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UnlinkAccountsRequest)) return false;
    UnlinkAccountsRequest o = (UnlinkAccountsRequest) other;
    return equals(twitter, o.twitter)
        && equals(facebook, o.facebook);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = twitter != null ? twitter.hashCode() : 0;
      result = result * 37 + (facebook != null ? facebook.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<UnlinkAccountsRequest> {

    public Boolean twitter;
    public Boolean facebook;

    public Builder() {
    }

    public Builder(UnlinkAccountsRequest message) {
      super(message);
      if (message == null) return;
      this.twitter = message.twitter;
      this.facebook = message.facebook;
    }

    /**
     * Determines whether or not to unlink your Twitter account.
     */
    public Builder twitter(Boolean twitter) {
      this.twitter = twitter;
      return this;
    }

    /**
     * Determines whether or not to unlink your Facebook account.
     */
    public Builder facebook(Boolean facebook) {
      this.facebook = facebook;
      return this;
    }

    @Override
    public UnlinkAccountsRequest build() {
      return new UnlinkAccountsRequest(this);
    }
  }
}
