// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/projects/TruckMuncher-Protos/com/truckmuncher/api/trucks.proto
package com.truckmuncher.api.trucks;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class ApprovalRequest extends Message {

  public static final String DEFAULT_TRUCKID = "";
  public static final String DEFAULT_EMAIL = "";

  /**
   * Suitable for unique identification.
   */
  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public final String truckId;

  /**
   * The best email address to contact the owner of the given truck.
   */
  @ProtoField(tag = 2, type = STRING, label = REQUIRED)
  public final String email;

  public ApprovalRequest(String truckId, String email) {
    this.truckId = truckId;
    this.email = email;
  }

  private ApprovalRequest(Builder builder) {
    this(builder.truckId, builder.email);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ApprovalRequest)) return false;
    ApprovalRequest o = (ApprovalRequest) other;
    return equals(truckId, o.truckId)
        && equals(email, o.email);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = truckId != null ? truckId.hashCode() : 0;
      result = result * 37 + (email != null ? email.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ApprovalRequest> {

    public String truckId;
    public String email;

    public Builder() {
    }

    public Builder(ApprovalRequest message) {
      super(message);
      if (message == null) return;
      this.truckId = message.truckId;
      this.email = message.email;
    }

    /**
     * Suitable for unique identification.
     */
    public Builder truckId(String truckId) {
      this.truckId = truckId;
      return this;
    }

    /**
     * The best email address to contact the owner of the given truck.
     */
    public Builder email(String email) {
      this.email = email;
      return this;
    }

    @Override
    public ApprovalRequest build() {
      checkRequiredFields();
      return new ApprovalRequest(this);
    }
  }
}
