// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/projects/TruckMuncher-Protos/com/truckmuncher/api/trucks.proto
package com.truckmuncher.api.trucks;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class ApprovalStatusResponse extends Message {

  public static final String DEFAULT_STATUS = "";

  /**
   * The current status of your approval
   */
  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public final String status;

  public ApprovalStatusResponse(String status) {
    this.status = status;
  }

  private ApprovalStatusResponse(Builder builder) {
    this(builder.status);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ApprovalStatusResponse)) return false;
    return equals(status, ((ApprovalStatusResponse) other).status);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = status != null ? status.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<ApprovalStatusResponse> {

    public String status;

    public Builder() {
    }

    public Builder(ApprovalStatusResponse message) {
      super(message);
      if (message == null) return;
      this.status = message.status;
    }

    /**
     * The current status of your approval
     */
    public Builder status(String status) {
      this.status = status;
      return this;
    }

    @Override
    public ApprovalStatusResponse build() {
      checkRequiredFields();
      return new ApprovalStatusResponse(this);
    }
  }
}
