// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/projects/TruckMuncher-Protos/com/truckmuncher/api/trucks.proto
package com.truckmuncher.api.trucks;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

public final class TruckProfilesResponse extends Message {

  public static final List<Truck> DEFAULT_TRUCKS = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<Truck> trucks;

  public TruckProfilesResponse(List<Truck> trucks) {
    this.trucks = immutableCopyOf(trucks);
  }

  private TruckProfilesResponse(Builder builder) {
    this(builder.trucks);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TruckProfilesResponse)) return false;
    return equals(trucks, ((TruckProfilesResponse) other).trucks);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = trucks != null ? trucks.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<TruckProfilesResponse> {

    public List<Truck> trucks;

    public Builder() {
    }

    public Builder(TruckProfilesResponse message) {
      super(message);
      if (message == null) return;
      this.trucks = copyOf(message.trucks);
    }

    public Builder trucks(List<Truck> trucks) {
      this.trucks = checkForNulls(trucks);
      return this;
    }

    @Override
    public TruckProfilesResponse build() {
      return new TruckProfilesResponse(this);
    }
  }
}
