// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/projects/TruckMuncher-Protos/com/truckmuncher/api/gcm.proto
package com.truckmuncher.api.gcm;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class GcmRegistrationRequest extends Message {

    public static final String DEFAULT_INSTALLATIONID = "";
    public static final String DEFAULT_GCMREGISTRATIONID = "";

    /**
     * Unique identifier for the installation
     */
    @ProtoField(tag = 1, type = STRING, label = REQUIRED)
    public final String installationId;

    @ProtoField(tag = 2, type = STRING)
    public final String gcmRegistrationId;

    public GcmRegistrationRequest(String installationId, String gcmRegistrationId) {
        this.installationId = installationId;
        this.gcmRegistrationId = gcmRegistrationId;
    }

    private GcmRegistrationRequest(Builder builder) {
        this(builder.installationId, builder.gcmRegistrationId);
        setBuilder(builder);
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) return true;
        if (!(other instanceof GcmRegistrationRequest)) return false;
        GcmRegistrationRequest o = (GcmRegistrationRequest) other;
        return equals(installationId, o.installationId)
                && equals(gcmRegistrationId, o.gcmRegistrationId);
    }

    @Override
    public int hashCode() {
        int result = hashCode;
        if (result == 0) {
            result = installationId != null ? installationId.hashCode() : 0;
            result = result * 37 + (gcmRegistrationId != null ? gcmRegistrationId.hashCode() : 0);
            hashCode = result;
        }
        return result;
    }

    public static final class Builder extends Message.Builder<GcmRegistrationRequest> {

        public String installationId;
        public String gcmRegistrationId;

        public Builder() {
        }

        public Builder(GcmRegistrationRequest message) {
            super(message);
            if (message == null) return;
            this.installationId = message.installationId;
            this.gcmRegistrationId = message.gcmRegistrationId;
        }

        /**
         * Unique identifier for the installation
         */
        public Builder installationId(String installationId) {
            this.installationId = installationId;
            return this;
        }

        public Builder gcmRegistrationId(String gcmRegistrationId) {
            this.gcmRegistrationId = gcmRegistrationId;
            return this;
        }

        @Override
        public GcmRegistrationRequest build() {
            checkRequiredFields();
            return new GcmRegistrationRequest(this);
        }
    }
}
