// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/projects/TruckMuncher-Protos/com/truckmuncher/api/gcm.proto
package com.truckmuncher.api.gcm;

import retrofit.Callback;
import retrofit.RetrofitError;
import retrofit.http.Body;
import retrofit.http.POST;

/**
 * The GcmService is used to register Android devices for push messages.
 */
public interface GcmService {
    @POST("/com.truckmuncher.api.gcm.GcmService/registerForGcm")
    GcmRegistrationResponse registerForGcm(@Body GcmRegistrationRequest request)
            throws RetrofitError;

    @POST("/com.truckmuncher.api.gcm.GcmService/registerForGcm")
    void registerForGcm(@Body GcmRegistrationRequest request, Callback<GcmRegistrationResponse> callback);
}
