// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Users/brettnockerts/Documents/TruckMuncher/TruckMuncher-Protos/com/truckmuncher/api/search.proto
package com.truckmuncher.api.search;

import retrofit.http.Body;
import retrofit.http.POST;

/**
 * The SearchService is used to offer full text search functionality to find trucks given filter criteria.
 */
public interface SearchService {
    /**
     * A simple search to find all trucks containing all terms in the given request
     */
    @POST("/com.truckmuncher.api.search.SearchService/simpleSearch")
    SimpleSearchResponse simpleSearch(@Body SimpleSearchRequest request);
}
