// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Users/brettnockerts/Documents/TruckMuncher/TruckMuncher-Protos/com/truckmuncher/api/search.proto
package com.truckmuncher.api.search;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import com.truckmuncher.api.menu.Menu;
import com.truckmuncher.api.trucks.Truck;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class SearchResponse extends Message {

    public static final String DEFAULT_BLURB = "";

    /**
     * A short contextual blurb including the search term. This highlights why this search result was included
     */
    @ProtoField(tag = 1, type = STRING, label = REQUIRED)
    public final String blurb;

    /**
     * The truck included in this specific search result
     */
    @ProtoField(tag = 2, label = REQUIRED)
    public final Truck truck;

    /**
     * The full menu belonging to the given truck
     */
    @ProtoField(tag = 3, label = REQUIRED)
    public final Menu menu;

    public SearchResponse(String blurb, Truck truck, Menu menu) {
        this.blurb = blurb;
        this.truck = truck;
        this.menu = menu;
    }

    private SearchResponse(Builder builder) {
        this(builder.blurb, builder.truck, builder.menu);
        setBuilder(builder);
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) return true;
        if (!(other instanceof SearchResponse)) return false;
        SearchResponse o = (SearchResponse) other;
        return equals(blurb, o.blurb)
                && equals(truck, o.truck)
                && equals(menu, o.menu);
    }

    @Override
    public int hashCode() {
        int result = hashCode;
        if (result == 0) {
            result = blurb != null ? blurb.hashCode() : 0;
            result = result * 37 + (truck != null ? truck.hashCode() : 0);
            result = result * 37 + (menu != null ? menu.hashCode() : 0);
            hashCode = result;
        }
        return result;
    }

    public static final class Builder extends Message.Builder<SearchResponse> {

        public String blurb;
        public Truck truck;
        public Menu menu;

        public Builder() {
        }

        public Builder(SearchResponse message) {
            super(message);
            if (message == null) return;
            this.blurb = message.blurb;
            this.truck = message.truck;
            this.menu = message.menu;
        }

        /**
         * A short contextual blurb including the search term. This highlights why this search result was included
         */
        public Builder blurb(String blurb) {
            this.blurb = blurb;
            return this;
        }

        /**
         * The truck included in this specific search result
         */
        public Builder truck(Truck truck) {
            this.truck = truck;
            return this;
        }

        /**
         * The full menu belonging to the given truck
         */
        public Builder menu(Menu menu) {
            this.menu = menu;
            return this;
        }

        @Override
        public SearchResponse build() {
            checkRequiredFields();
            return new SearchResponse(this);
        }
    }
}
