// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/Dropbox/workspace/TruckMuncher-Protos/com/truckmuncher/api/menu.proto
package com.truckmuncher.api.menu;

import com.squareup.wire.Message;

public final class DeleteCategoryResponse extends Message {

    public DeleteCategoryResponse() {
    }

    private DeleteCategoryResponse(Builder builder) {
        setBuilder(builder);
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof DeleteCategoryResponse;
    }

    @Override
    public int hashCode() {
        return 0;
    }

    public static final class Builder extends Message.Builder<DeleteCategoryResponse> {

        public Builder() {
        }

        public Builder(DeleteCategoryResponse message) {
            super(message);
        }

        @Override
        public DeleteCategoryResponse build() {
            return new DeleteCategoryResponse(this);
        }
    }
}
