// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/Dropbox/workspace/TruckMuncher-Protos/com/truckmuncher/api/menu.proto
package com.truckmuncher.api.menu;

import com.squareup.wire.Message;

public final class DeleteMenuItemResponse extends Message {

  public DeleteMenuItemResponse() {
  }

  private DeleteMenuItemResponse(Builder builder) {
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    return other instanceof DeleteMenuItemResponse;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public static final class Builder extends Message.Builder<DeleteMenuItemResponse> {

    public Builder() {
    }

    public Builder(DeleteMenuItemResponse message) {
      super(message);
    }

    @Override
    public DeleteMenuItemResponse build() {
      return new DeleteMenuItemResponse(this);
    }
  }
}
