// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/Dropbox/workspace/TruckMuncher-Protos/com/truckmuncher/api/menu.proto
package com.truckmuncher.api.menu;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class DeleteMenuItemRequest extends Message {

  public static final String DEFAULT_MENUITEMID = "";

  /**
   * Suitable for unique identification.
   */
  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public final String menuItemId;

  public DeleteMenuItemRequest(String menuItemId) {
    this.menuItemId = menuItemId;
  }

  private DeleteMenuItemRequest(Builder builder) {
    this(builder.menuItemId);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof DeleteMenuItemRequest)) return false;
    return equals(menuItemId, ((DeleteMenuItemRequest) other).menuItemId);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = menuItemId != null ? menuItemId.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<DeleteMenuItemRequest> {

    public String menuItemId;

    public Builder() {
    }

    public Builder(DeleteMenuItemRequest message) {
      super(message);
      if (message == null) return;
      this.menuItemId = message.menuItemId;
    }

    /**
     * Suitable for unique identification.
     */
    public Builder menuItemId(String menuItemId) {
      this.menuItemId = menuItemId;
      return this;
    }

    @Override
    public DeleteMenuItemRequest build() {
      checkRequiredFields();
      return new DeleteMenuItemRequest(this);
    }
  }
}
