// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/Dropbox/workspace/TruckMuncher-Protos/com/truckmuncher/api/menu.proto
package com.truckmuncher.api.menu;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Label.REPEATED;

/**
 * WARNING: The MenmuItem availability will only be set if the request specified that it should be.
 */
public final class FullMenusResponse extends Message {

  public static final List<Menu> DEFAULT_MENUS = Collections.emptyList();

  @ProtoField(tag = 1, label = REPEATED)
  public final List<Menu> menus;

  public FullMenusResponse(List<Menu> menus) {
    this.menus = immutableCopyOf(menus);
  }

  private FullMenusResponse(Builder builder) {
    this(builder.menus);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof FullMenusResponse)) return false;
    return equals(menus, ((FullMenusResponse) other).menus);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = menus != null ? menus.hashCode() : 1);
  }

  public static final class Builder extends Message.Builder<FullMenusResponse> {

    public List<Menu> menus;

    public Builder() {
    }

    public Builder(FullMenusResponse message) {
      super(message);
      if (message == null) return;
      this.menus = copyOf(message.menus);
    }

    public Builder menus(List<Menu> menus) {
      this.menus = checkForNulls(menus);
      return this;
    }

    @Override
    public FullMenusResponse build() {
      return new FullMenusResponse(this);
    }
  }
}
