// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/Dropbox/workspace/TruckMuncher-Protos/com/truckmuncher/api/menu.proto
package com.truckmuncher.api.menu;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.DOUBLE;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * The latitude/longitude are used to determine the Region in which the user is. This will scope the diff to just those MenuItems.
 * The version is optional and if specified will be used to reduce the diff size.
 */
public final class MenuItemAvailabilityDiffRequest extends Message {

    public static final Double DEFAULT_LATITUDE = 0D;
    public static final Double DEFAULT_LONGITUDE = 0D;
    public static final Long DEFAULT_VERSION = 0L;

    /**
     * Value in the range [-90, 90]
     */
    @ProtoField(tag = 1, type = DOUBLE, label = REQUIRED)
    public final Double latitude;

    /**
     * Value in the range [-180, 180]
     */
    @ProtoField(tag = 2, type = DOUBLE, label = REQUIRED)
    public final Double longitude;

    /**
     * The latest version of MenuItem availability that the client has. If 0 is specified, availability for every MenuItem is returned.
     * A negative value will result in an error.
     */
    @ProtoField(tag = 3, type = INT64)
    public final Long version;

    public MenuItemAvailabilityDiffRequest(Double latitude, Double longitude, Long version) {
        this.latitude = latitude;
        this.longitude = longitude;
        this.version = version;
    }

    private MenuItemAvailabilityDiffRequest(Builder builder) {
        this(builder.latitude, builder.longitude, builder.version);
        setBuilder(builder);
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) return true;
        if (!(other instanceof MenuItemAvailabilityDiffRequest)) return false;
        MenuItemAvailabilityDiffRequest o = (MenuItemAvailabilityDiffRequest) other;
        return equals(latitude, o.latitude)
                && equals(longitude, o.longitude)
                && equals(version, o.version);
    }

    @Override
    public int hashCode() {
        int result = hashCode;
        if (result == 0) {
            result = latitude != null ? latitude.hashCode() : 0;
            result = result * 37 + (longitude != null ? longitude.hashCode() : 0);
            result = result * 37 + (version != null ? version.hashCode() : 0);
            hashCode = result;
        }
        return result;
    }

    public static final class Builder extends Message.Builder<MenuItemAvailabilityDiffRequest> {

        public Double latitude;
        public Double longitude;
        public Long version;

        public Builder() {
        }

        public Builder(MenuItemAvailabilityDiffRequest message) {
            super(message);
            if (message == null) return;
            this.latitude = message.latitude;
            this.longitude = message.longitude;
            this.version = message.version;
        }

        /**
         * Value in the range [-90, 90]
         */
        public Builder latitude(Double latitude) {
            this.latitude = latitude;
            return this;
        }

        /**
         * Value in the range [-180, 180]
         */
        public Builder longitude(Double longitude) {
            this.longitude = longitude;
            return this;
        }

        /**
         * The latest version of MenuItem availability that the client has. If 0 is specified, availability for every MenuItem is returned.
         * A negative value will result in an error.
         */
        public Builder version(Long version) {
            this.version = version;
            return this;
        }

        @Override
        public MenuItemAvailabilityDiffRequest build() {
            checkRequiredFields();
            return new MenuItemAvailabilityDiffRequest(this);
        }
    }
}
