// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/projects/TruckMuncher-Protos/com/truckmuncher/api/menu.proto
package com.truckmuncher.api.menu;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class MenuRequest extends Message {

  public static final String DEFAULT_TRUCKID = "";

  /**
   * Suitable for unique identification.
   */
  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public final String truckId;

  public MenuRequest(String truckId) {
    this.truckId = truckId;
  }

  private MenuRequest(Builder builder) {
    this(builder.truckId);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof MenuRequest)) return false;
    return equals(truckId, ((MenuRequest) other).truckId);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = truckId != null ? truckId.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<MenuRequest> {

    public String truckId;

    public Builder() {
    }

    public Builder(MenuRequest message) {
      super(message);
      if (message == null) return;
      this.truckId = message.truckId;
    }

    /**
     * Suitable for unique identification.
     */
    public Builder truckId(String truckId) {
      this.truckId = truckId;
      return this;
    }

    @Override
    public MenuRequest build() {
      checkRequiredFields();
      return new MenuRequest(this);
    }
  }
}
