// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/Dropbox/workspace/TruckMuncher-Protos/com/truckmuncher/api/menu.proto
package com.truckmuncher.api.menu;

import retrofit.Callback;
import retrofit.RetrofitError;
import retrofit.http.Body;
import retrofit.http.POST;

/**
 * The MenuService is used to interact with menus. The service is built to separate persistent state from volatile state when possible.
 */
public interface MenuService {
    /**
     * Get the changes in MenuItem availability since the last sync.
     */
    @POST("/com.truckmuncher.api.menu.MenuService/getMenuItemAvailabilityDiff")
    MenuItemAvailabilityDiffResponse getMenuItemAvailabilityDiff(@Body MenuItemAvailabilityDiffRequest request)
            throws RetrofitError;

    /**
     * Get the changes in MenuItem availability since the last sync.
     */
    @POST("/com.truckmuncher.api.menu.MenuService/getMenuItemAvailabilityDiff")
    void getMenuItemAvailabilityDiff(@Body MenuItemAvailabilityDiffRequest request, Callback<MenuItemAvailabilityDiffResponse> callback);

    /**
     * Get all of the menus in the user's region.
     */
    @POST("/com.truckmuncher.api.menu.MenuService/getFullMenus")
    FullMenusResponse getFullMenus(@Body FullMenusRequest request)
            throws RetrofitError;

    /**
     * Get all of the menus in the user's region.
     */
    @POST("/com.truckmuncher.api.menu.MenuService/getFullMenus")
    void getFullMenus(@Body FullMenusRequest request, Callback<FullMenusResponse> callback);

    /**
     * Use this to get the menu that a vendor should see when editing their own menu.
     * <p/>
     * This call requires Vendor authorization
     */
    @POST("/com.truckmuncher.api.menu.MenuService/getVendorMenu")
    VendorMenuResponse getVendorMenu(@Body VendorMenuRequest request)
            throws RetrofitError;

    /**
     * Use this to get the menu that a vendor should see when editing their own menu.
     * <p/>
     * This call requires Vendor authorization
     */
    @POST("/com.truckmuncher.api.menu.MenuService/getVendorMenu")
    void getVendorMenu(@Body VendorMenuRequest request, Callback<VendorMenuResponse> callback);

    /**
     * Declare which MenuItems are changing in availability. This call will increment the version number of the MenuItem availability.
     * This call does not provide any sort of versioning protection, and will simple apply the changes to the latest version available.
     * <p/>
     * This call requires Vendor authorization
     */
    @POST("/com.truckmuncher.api.menu.MenuService/modifyMenuAvailability")
    MenuAvailabilityResponse modifyMenuAvailability(@Body MenuAvailabilityRequest request)
            throws RetrofitError;

    /**
     * Declare which MenuItems are changing in availability. This call will increment the version number of the MenuItem availability.
     * This call does not provide any sort of versioning protection, and will simple apply the changes to the latest version available.
     * <p/>
     * This call requires Vendor authorization
     */
    @POST("/com.truckmuncher.api.menu.MenuService/modifyMenuAvailability")
    void modifyMenuAvailability(@Body MenuAvailabilityRequest request, Callback<MenuAvailabilityResponse> callback);
}
