// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/Dropbox/workspace/TruckMuncher-Protos/com/truckmuncher/api/menu.proto
package com.truckmuncher.api.menu;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class MenuAvailabilityResponse extends Message {

  public static final Long DEFAULT_VERSION = 0L;

  /**
   * The new version of MenuItemAvailability.
   */
  @ProtoField(tag = 1, type = INT64, label = REQUIRED)
  public final Long version;

  public MenuAvailabilityResponse(Long version) {
    this.version = version;
  }

  private MenuAvailabilityResponse(Builder builder) {
    this(builder.version);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof MenuAvailabilityResponse)) return false;
    return equals(version, ((MenuAvailabilityResponse) other).version);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = version != null ? version.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<MenuAvailabilityResponse> {

    public Long version;

    public Builder() {
    }

    public Builder(MenuAvailabilityResponse message) {
      super(message);
      if (message == null) return;
      this.version = message.version;
    }

    /**
     * The new version of MenuItemAvailability.
     */
    public Builder version(Long version) {
      this.version = version;
      return this;
    }

    @Override
    public MenuAvailabilityResponse build() {
      checkRequiredFields();
      return new MenuAvailabilityResponse(this);
    }
  }
}
