// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Volumes/home/Dropbox/workspace/TruckMuncher-Protos/com/truckmuncher/api/menu.proto
package com.truckmuncher.api.menu;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Label.REQUIRED;

public final class VendorMenuResponse extends Message {

    @ProtoField(tag = 1, label = REQUIRED)
    public final Menu menu;

    public VendorMenuResponse(Menu menu) {
        this.menu = menu;
    }

    private VendorMenuResponse(Builder builder) {
        this(builder.menu);
        setBuilder(builder);
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) return true;
        if (!(other instanceof VendorMenuResponse)) return false;
        return equals(menu, ((VendorMenuResponse) other).menu);
    }

    @Override
    public int hashCode() {
        int result = hashCode;
        return result != 0 ? result : (hashCode = menu != null ? menu.hashCode() : 0);
    }

    public static final class Builder extends Message.Builder<VendorMenuResponse> {

        public Menu menu;

        public Builder() {
        }

        public Builder(VendorMenuResponse message) {
            super(message);
            if (message == null) return;
            this.menu = message.menu;
        }

        public Builder menu(Menu menu) {
            this.menu = menu;
            return this;
        }

        @Override
        public VendorMenuResponse build() {
            checkRequiredFields();
            return new VendorMenuResponse(this);
        }
    }
}
